#!/bin/bash
# ============================================================================
# Create Run Scripts - Generate helper scripts for pipeline steps
# ============================================================================
# This script creates 3 helper scripts in the output directory to run the
# remaining pipeline steps (2, 3, 4) with the correct paths pre-configured.
#
# Usage:
#   ./create_run_scripts.sh <output_directory>
#
# Example:
#   ./create_run_scripts.sh output/pipeline_run/20251210_142323
#
# This will create in the output directory:
#   - run_gprmax.sh       (Step 2: Run simulations)
#   - extract_features.sh (Step 3: Extract features)
#   - create_blueprints.sh (Step 4: Create blueprints)
# ============================================================================

set -e

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Check arguments
if [ $# -eq 0 ]; then
    echo -e "${RED}Error: Output directory required${NC}"
    echo ""
    echo "Usage: $0 <output_directory>"
    echo ""
    echo "Example:"
    echo "  $0 output/pipeline_run/20251210_142323"
    exit 1
fi

OUTPUT_DIR="$1"

# Validate directory exists
if [ ! -d "$OUTPUT_DIR" ]; then
    echo -e "${RED}Error: Directory not found: $OUTPUT_DIR${NC}"
    exit 1
fi

# Get absolute path
OUTPUT_DIR=$(cd "$OUTPUT_DIR" && pwd)

# Get project root (assuming this script is in project root)
PROJECT_ROOT=$(cd "$(dirname "$0")" && pwd)

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE} Creating Run Scripts${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo "Output directory: $OUTPUT_DIR"
echo "Project root:     $PROJECT_ROOT"
echo ""

# ============================================================================
# Script 1: run_gprmax.sh
# ============================================================================

cat > "$OUTPUT_DIR/run_gprmax.sh" << 'SCRIPT1'
#!/bin/bash
# Auto-generated script to run gprMax simulations
# Generated by create_run_scripts.sh

set -e

GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Configuration
PARALLEL=${1:-1}  # Default to 1 parallel process, or use first argument
FORCE=false

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -p|--parallel)
            PARALLEL="$2"
            shift 2
            ;;
        -f|--force)
            FORCE=true
            shift
            ;;
        *)
            shift
            ;;
    esac
done

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE} Running gprMax Simulations${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo "Directory:  $(pwd)"
echo "Parallel:   $PARALLEL"
echo "Force:      $FORCE"
echo ""

TOTAL=$(ls -1 *.in 2>/dev/null | wc -l)

if [ "$TOTAL" -eq 0 ]; then
    echo -e "${RED}No .in files found${NC}"
    exit 1
fi

echo -e "${BLUE}Found $TOTAL .in files${NC}"
echo ""

PROCESSED=0
SKIPPED=0
FAILED=0

for in_file in *.in; do
    if [ -f "$in_file" ]; then
        out_file="${in_file%.in}.out"
        
        if [ -f "$out_file" ] && [ "$FORCE" = false ]; then
            echo -e "${YELLOW}⏭️  Skipping $in_file (output exists)${NC}"
            ((SKIPPED++))
            continue
        fi
        
        echo -n "Processing $in_file [$((PROCESSED+SKIPPED+FAILED+1))/$TOTAL]... "
        
        if python -m gprMax "$in_file" -n "$PARALLEL" > /dev/null 2>&1; then
            echo -e "${GREEN}✓${NC}"
            ((PROCESSED++))
        else
            echo -e "${RED}✗${NC}"
            ((FAILED++))
        fi
    fi
done

echo ""
echo -e "${BLUE}========================================${NC}"
echo "Summary:"
echo "  ✅ Processed: $PROCESSED"
echo "  ⏭️  Skipped:   $SKIPPED"
echo "  ❌ Failed:    $FAILED"
echo -e "${BLUE}========================================${NC}"

if [ "$PROCESSED" -gt 0 ]; then
    echo ""
    echo -e "${GREEN}✅ Simulations complete!${NC}"
    echo ""
    echo "Next step:"
    echo "  ./extract_features.sh"
fi
SCRIPT1

chmod +x "$OUTPUT_DIR/run_gprmax.sh"
echo -e "${GREEN}✓${NC} Created run_gprmax.sh"

# ============================================================================
# Script 2: extract_features.sh
# ============================================================================

cat > "$OUTPUT_DIR/extract_features.sh" << SCRIPT2
#!/bin/bash
# Auto-generated script to extract features
# Generated by create_run_scripts.sh

set -e

GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "\${BLUE}========================================\${NC}"
echo -e "\${BLUE} Extracting Features\${NC}"
echo -e "\${BLUE}========================================\${NC}"
echo ""
echo "Directory: \$(pwd)"
echo ""

# Check for .out files
OUT_COUNT=\$(ls -1 *.out 2>/dev/null | wc -l)

if [ "\$OUT_COUNT" -eq 0 ]; then
    echo -e "\${RED}Error: No .out files found${NC}"
    echo "Run ./run_gprmax.sh first"
    exit 1
fi

echo -e "\${BLUE}Found \$OUT_COUNT .out files\${NC}"
echo ""

# Run feature extraction
python "$PROJECT_ROOT/create_feature_dataset.py" "\$(pwd)"

if [ \$? -eq 0 ]; then
    if [ -f "features.csv" ]; then
        echo ""
        echo -e "\${GREEN}✅ Feature extraction complete!\${NC}"
        
        FEATURE_COUNT=\$(head -1 features.csv | tr ',' '\n' | wc -l)
        SAMPLE_COUNT=\$(tail -n +2 features.csv | wc -l)
        
        echo ""
        echo "Statistics:"
        echo "  Features:  \$FEATURE_COUNT"
        echo "  Samples:   \$SAMPLE_COUNT"
        echo ""
        echo "Next step:"
        echo "  ./create_blueprints.sh"
    fi
else
    echo -e "\${RED}❌ Feature extraction failed\${NC}"
    exit 1
fi
SCRIPT2

chmod +x "$OUTPUT_DIR/extract_features.sh"
echo -e "${GREEN}✓${NC} Created extract_features.sh"

# ============================================================================
# Script 3: create_blueprints.sh
# ============================================================================

cat > "$OUTPUT_DIR/create_blueprints.sh" << SCRIPT3
#!/bin/bash
# Auto-generated script to create blueprints
# Generated by create_run_scripts.sh

set -e

GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Configuration
FORCE=false
SHOW=false

# Parse arguments
while [[ \$# -gt 0 ]]; do
    case \$1 in
        -f|--force)
            FORCE=true
            shift
            ;;
        -s|--show)
            SHOW=true
            shift
            ;;
        *)
            shift
            ;;
    esac
done

BLUEPRINT_SCRIPT="$PROJECT_ROOT/scripts/tools/visualization/visualize_gprmax_blueprint.py"

if [ ! -f "\$BLUEPRINT_SCRIPT" ]; then
    echo -e "\${RED}Error: Blueprint script not found\${NC}"
    exit 1
fi

echo -e "\${BLUE}========================================\${NC}"
echo -e "\${BLUE} Creating Blueprints\${NC}"
echo -e "\${BLUE}========================================\${NC}"
echo ""
echo "Directory: \$(pwd)"
echo "Force:     \$FORCE"
echo "Show:      \$SHOW"
echo ""

TOTAL=\$(ls -1 *.in 2>/dev/null | wc -l)

if [ "\$TOTAL" -eq 0 ]; then
    echo -e "\${RED}No .in files found\${NC}"
    exit 1
fi

echo -e "\${BLUE}Found \$TOTAL .in files\${NC}"
echo ""

PROCESSED=0
SKIPPED=0
FAILED=0

for in_file in *.in; do
    if [ -f "\$in_file" ]; then
        basename_no_ext=\$(basename "\$in_file" .in)
        blueprint_file="\${basename_no_ext}_blueprint.png"
        
        if [ -f "\$blueprint_file" ] && [ "\$FORCE" = false ]; then
            echo -e "\${YELLOW}⏭️  Skipping \$in_file (blueprint exists)\${NC}"
            ((SKIPPED++))
            continue
        fi
        
        echo -n "Creating blueprint for \$in_file [\$((PROCESSED+SKIPPED+FAILED+1))/\$TOTAL]... "
        
        if [ "\$SHOW" = true ]; then
            if python "\$BLUEPRINT_SCRIPT" "\$in_file" -o "\$blueprint_file" 2>&1 | grep -q "ERROR"; then
                echo -e "\${RED}✗\${NC}"
                ((FAILED++))
            else
                echo -e "\${GREEN}✓\${NC}"
                ((PROCESSED++))
            fi
        else
            if python "\$BLUEPRINT_SCRIPT" "\$in_file" -o "\$blueprint_file" --no-show > /dev/null 2>&1; then
                echo -e "\${GREEN}✓\${NC}"
                ((PROCESSED++))
            else
                echo -e "\${RED}✗\${NC}"
                ((FAILED++))
            fi
        fi
    fi
done

echo ""
echo -e "\${BLUE}========================================\${NC}"
echo "Summary:"
echo "  ✅ Created:  \$PROCESSED"
echo "  ⏭️  Skipped:  \$SKIPPED"
echo "  ❌ Failed:   \$FAILED"
echo -e "\${BLUE}========================================\${NC}"

if [ "\$PROCESSED" -gt 0 ]; then
    echo ""
    echo -e "\${GREEN}✅ Blueprints created!\${NC}"
    echo ""
    echo "View blueprints:"
    echo "  open *_blueprint.png"
fi
SCRIPT3

chmod +x "$OUTPUT_DIR/create_blueprints.sh"
echo -e "${GREEN}✓${NC} Created create_blueprints.sh"

# ============================================================================
# Create README
# ============================================================================

cat > "$OUTPUT_DIR/README.txt" << README
Pipeline Run Scripts
====================

This directory contains auto-generated scripts to run the remaining pipeline steps.

Usage:
------

1. Run gprMax simulations:
   ./run_gprmax.sh
   
   With options:
   ./run_gprmax.sh -p 4        # Use 4 parallel processes
   ./run_gprmax.sh -f          # Force re-run existing files

2. Extract features:
   ./extract_features.sh

3. Create blueprints:
   ./create_blueprints.sh
   
   With options:
   ./create_blueprints.sh -f   # Force re-create existing blueprints
   ./create_blueprints.sh -s   # Show blueprints after creation

Run all remaining steps:
------------------------
./run_gprmax.sh -p 4 && ./extract_features.sh && ./create_blueprints.sh

Directory: $OUTPUT_DIR
Generated: $(date)
README

echo -e "${GREEN}✓${NC} Created README.txt"

echo ""
echo -e "${BLUE}========================================${NC}"
echo -e "${GREEN}✅ All scripts created successfully!${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo "Created in: $OUTPUT_DIR"
echo ""
echo "Scripts:"
echo "  1. run_gprmax.sh       - Run simulations"
echo "  2. extract_features.sh - Extract features"
echo "  3. create_blueprints.sh - Create blueprints"
echo ""
echo "To run:"
echo "  cd $OUTPUT_DIR"
echo "  ./run_gprmax.sh -p 4"
echo "  ./extract_features.sh"
echo "  ./create_blueprints.sh"
echo ""
