#!/usr/bin/env python3
"""
Bayesian layer calibration: optuna TPE on fast 2D gprMax simulations.

Each trial generates a minimal 2D .in file (250×1×630 cells, ~5 s on CPU),
runs gprMax, then computes Pearson r between the synthetic Ey coda and a real
DZT trace in the 4–20 ns window after the direct wave.

Layer geometry is fixed (from scene_3d_5layer_split_natgnd_e14):
  deep_natgnd  0.00–0.15 m   [subgrade]
  natgnd_upper 0.15–0.30 m
  bedrock      0.30–0.40 m
  formation    0.40–0.50 m
  subballast   0.50–0.65 m
  ballast_void 0.65–1.00 m   (eps=4.5, no rocks — flat layer proxy)
  standoff     1.00–1.05 m   (air)
  source/rx    z=1.052 m     (y-polarised Hertzian dipole, Ricker 400 MHz)

Free parameters (8):
  subballast_eps, formation_eps, bedrock_eps, natgnd_upper_eps, deep_natgnd_eps
  formation_sigma, natgnd_upper_sigma, deep_natgnd_sigma

Usage:
    python scripts/calibration/calibrate_layers.py \\
        --dzt "D:/Codigo/Data/...DZT" --trace 77000 \\
        --trials 100 --study calib_v1
"""
import argparse
import subprocess
import sys
from pathlib import Path

import h5py
import numpy as np
from scipy.signal import hilbert

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

# ── Paths ─────────────────────────────────────────────────────────────────────
REPO      = Path(__file__).resolve().parents[2]
WORK_DIR  = REPO / "experiments" / "calibration" / "trials"
STUDY_DIR = REPO / "experiments" / "calibration"

GPRMAX_PY   = r"C:\Users\barba\.conda\envs\gprMax\python.exe"
MINICONDA_PY = r"C:\Users\barba\miniconda3\python.exe"

# ── Fixed geometry ─────────────────────────────────────────────────────────────
DX       = 0.002
DEEP_H   = 0.15
NUP_H    = 0.15
BED_H    = 0.10
FORM_H   = 0.10
SUB_H    = 0.15
BALL_H   = 0.35
STANDOFF = 0.05
DOM_Z    = 1.26
DOM_X    = 0.50

# Fixed eps (validated)
EPS_BALL_VOID = 4.5
SIG_BALL_VOID = 0.001
EPS_GRANITE   = 6.1

# Fixed sigma for low-sensitivity layers
SIG_SUBBALLAST = 0.005
SIG_BEDROCK    = 0.001

# Parameter bounds
BOUNDS = {
    "subballast_eps":      (5.0, 12.0),   # widened: was 9.0 (hit upper bound in v2)
    "formation_eps":       (5.0, 15.0),   # widened: was 7.0 (hit lower bound in v2)
    "bedrock_eps":         (5.0, 14.0),   # widened: was 9.0 (hit upper bound in v4)
    "natgnd_upper_eps":    (8.0, 18.0),
    "deep_natgnd_eps":    (10.0, 24.0),
    "formation_sigma":    (0.002, 0.030),
    "natgnd_upper_sigma": (0.005, 0.060),
    "deep_natgnd_sigma":  (0.001, 0.025),
}

# Coda comparison window (ns after DW peak)
CODA_START_NS = 4.0
CODA_END_NS   = 20.0


# ── 2D .in file writer ────────────────────────────────────────────────────────
def write_2d_in(params: dict, in_path: Path) -> None:
    """Write a minimal flat-layer 2D gprMax .in file from params dict."""
    z0 = 0.0
    z1 = z0 + DEEP_H
    z2 = z1 + NUP_H
    z3 = z2 + BED_H
    z4 = z3 + FORM_H
    z5 = z4 + SUB_H
    z6 = z5 + BALL_H
    src_z = z6 + STANDOFF + DX   # just above skid
    dom_y = DX                    # single cell → 2D
    src_x = DOM_X / 2
    src_y = DX / 2

    def f(v): return f"{v:.6f}"

    lines = [
        "## 2D calibration - generated by calibrate_layers.py",
        f"#domain: {DOM_X} {dom_y} {DOM_Z}",
        f"#dx_dy_dz: {DX} {DX} {DX}",
        "#time_window: 30e-9",
        "",
        "## Materials",
        f"#material: {EPS_BALL_VOID} {SIG_BALL_VOID} 1.0 0.0 ballast_void",
        f"#material: {f(params['subballast_eps'])} {SIG_SUBBALLAST} 1.0 0.0 subballast",
        f"#material: {f(params['formation_eps'])} {f(params['formation_sigma'])} 1.0 0.0 formation",
        f"#material: {f(params['bedrock_eps'])} {SIG_BEDROCK} 1.0 0.0 bedrock",
        f"#material: {f(params['natgnd_upper_eps'])} {f(params['natgnd_upper_sigma'])} 1.0 0.0 natgnd_upper",
        f"#material: {f(params['deep_natgnd_eps'])} {f(params['deep_natgnd_sigma'])} 1.0 0.0 deep_natgnd",
        "",
        "## Geometry (Z-up, bottom to top)",
        f"#box: 0 0 {f(z0)} {DOM_X} {dom_y} {f(z1)} deep_natgnd",
        f"#box: 0 0 {f(z1)} {DOM_X} {dom_y} {f(z2)} natgnd_upper",
        f"#box: 0 0 {f(z2)} {DOM_X} {dom_y} {f(z3)} bedrock",
        f"#box: 0 0 {f(z3)} {DOM_X} {dom_y} {f(z4)} formation",
        f"#box: 0 0 {f(z4)} {DOM_X} {dom_y} {f(z5)} subballast",
        f"#box: 0 0 {f(z5)} {DOM_X} {dom_y} {f(z6)} ballast_void",
        "",
        "## Source and receiver - y-polarised Hertzian dipole, Ricker 400 MHz",
        "#waveform: ricker 1 4e8 ricker400",
        f"#hertzian_dipole: y {src_x} {src_y} {f(src_z)} ricker400",
        f"#rx: {src_x} {src_y} {f(src_z)}",
    ]
    in_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


# ── gprMax runner ─────────────────────────────────────────────────────────────
def run_gprmax_2d(in_path: Path, timeout: int = 120) -> bool:
    """Run gprMax on in_path (2D, CPU). Returns True on success."""
    result = subprocess.run(
        [GPRMAX_PY, "-m", "gprMax", str(in_path)],
        capture_output=True,
        timeout=timeout,
        cwd=str(in_path.parent),
    )
    return result.returncode == 0 and in_path.with_suffix(".out").exists()


# ── Waveform loading ──────────────────────────────────────────────────────────
def _envelope(y: np.ndarray) -> np.ndarray:
    """Hilbert envelope, normalised to peak=1."""
    env = np.abs(hilbert(y))
    peak = env.max() if env.max() > 0 else 1.0
    return env / peak


def load_syn_coda(out_path: Path):
    """Return (t_rel_ns, env_norm) — Hilbert envelope in coda window."""
    with h5py.File(out_path, "r") as f:
        dt_ns = float(f.attrs["dt"]) * 1e9
        ey = f["rxs/rx1/Ey"][:]
    t = np.arange(len(ey)) * dt_ns
    dw_idx = int(np.argmax(np.abs(ey[:int(6 / dt_ns)])))
    t_rel = t - t[dw_idx]
    mask = (t_rel >= CODA_START_NS) & (t_rel <= CODA_END_NS)
    t_c  = t_rel[mask]
    env  = _envelope(ey[mask])
    return t_c, env


def load_real_coda(dzt_path: str, trace_idx: int):
    """Return (t_rel_ns, env_norm, dt_ns) — Hilbert envelope of real DZT coda."""
    raw = np.fromfile(dzt_path, dtype=np.int32, offset=131072)
    n_traces = len(raw) // 512
    trace = raw[: n_traces * 512].reshape(n_traces, 512)[trace_idx, 2:].astype(np.float64)
    dt_ns = 50.0 / 511.0
    t = np.arange(len(trace)) * dt_ns
    dw_idx = int(np.argmax(np.abs(trace[:int(10 / dt_ns)])))
    t_rel = t - t[dw_idx]
    mask = (t_rel >= CODA_START_NS) & (t_rel <= CODA_END_NS)
    t_c  = t_rel[mask]
    env  = _envelope(trace[mask])
    return t_c, env, dt_ns


# ── Objective ─────────────────────────────────────────────────────────────────
def pearson_r(y1: np.ndarray, y2: np.ndarray) -> float:
    if np.std(y1) < 1e-12 or np.std(y2) < 1e-12:
        return -1.0
    r = float(np.corrcoef(y1, y2)[0, 1])
    return r if not np.isnan(r) else -1.0


def make_objective(t_real, y_real, dzt_path, trace_idx):
    """Return an optuna objective closure."""

    def objective(trial):
        params = {k: trial.suggest_float(k, lo, hi) for k, (lo, hi) in BOUNDS.items()}

        in_path  = WORK_DIR / f"trial_{trial.number:05d}.in"
        out_path = in_path.with_suffix(".out")
        vti_path = in_path.with_suffix(".vti")

        try:
            write_2d_in(params, in_path)
            ok = run_gprmax_2d(in_path)
            if not ok:
                return 1.0   # worst (we minimize -r, so 1.0 = r = -1)

            t_syn, env_syn = load_syn_coda(out_path)
            # Envelope is always positive — no polarity flip needed
            env_interp = np.interp(t_real, t_syn, env_syn, left=0.0, right=0.0)
            r = pearson_r(env_interp, y_real)
            return -r   # minimise → maximise r

        except Exception as exc:
            print(f"  [trial {trial.number}] ERROR: {exc}")
            return 1.0

        finally:
            for p in (in_path, out_path, vti_path):
                if p and p.exists():
                    p.unlink(missing_ok=True)

    return objective


# ── Entry point ───────────────────────────────────────────────────────────────
def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dzt", required=True,
                    help="Path to DZT file")
    ap.add_argument("--trace", type=int, default=77000,
                    help="Trace index (default 77000)")
    ap.add_argument("--trials", type=int, default=100,
                    help="Number of optuna trials (default 100)")
    ap.add_argument("--study", default="calib_v1",
                    help="Study name — used for SQLite storage (default calib_v1)")
    ap.add_argument("--seed", type=int, default=42,
                    help="Sampler seed (default 42)")
    args = ap.parse_args()

    WORK_DIR.mkdir(parents=True, exist_ok=True)
    STUDY_DIR.mkdir(parents=True, exist_ok=True)
    db_path = STUDY_DIR / f"{args.study}.db"

    print(f"Loading real DZT trace #{args.trace} …")
    t_real, y_real, _ = load_real_coda(args.dzt, args.trace)
    print(f"  coda window: {t_real[0]:.1f}–{t_real[-1]:.1f} ns  ({len(t_real)} samples)")

    print(f"\nStarting optuna study '{args.study}' — {args.trials} trials")
    print(f"  storage: {db_path}")
    print(f"  work dir: {WORK_DIR}\n")

    import optuna
    optuna.logging.set_verbosity(optuna.logging.WARNING)

    sampler = optuna.samplers.TPESampler(seed=args.seed)
    study = optuna.create_study(
        study_name=args.study,
        direction="minimize",
        sampler=sampler,
        storage=f"sqlite:///{db_path}",
        load_if_exists=True,
    )

    objective = make_objective(t_real, y_real, args.dzt, args.trace)

    completed = len([t for t in study.trials if t.state.name == "COMPLETE"])
    remaining = max(0, args.trials - completed)
    print(f"Already completed: {completed}  |  running: {remaining}\n")

    for i in range(remaining):
        trial = study.ask()
        val = objective(trial)
        study.tell(trial, val)
        best = study.best_value
        r_cur = -val
        r_best = -best
        print(f"  trial {trial.number:4d}  r={r_cur:+.4f}  best_r={r_best:+.4f}  "
              + "  ".join(f"{k}={trial.params[k]:.3f}" for k in list(BOUNDS)[:3]) + " …")

    best = study.best_trial
    print(f"\n{'='*60}")
    print(f"Best trial: #{best.number}  r={-best.value:.4f}")
    print("Parameters:")
    for k, v in best.params.items():
        lo, hi = BOUNDS[k]
        print(f"  {k:<26} = {v:.5f}   (bounds [{lo}, {hi}])")

    # Save best params as TOML snippet
    snippet_path = STUDY_DIR / f"{args.study}_best.toml"
    lines = [
        f"# Best trial #{best.number}  r={-best.value:.4f}",
        f"# Run verify_best.py to confirm in 3D\n",
        "[archie]",
        "rho_w = 8.0  # effective calibrated value\n",
        "[materials.subgrade]",
        f"eps   = {best.params['deep_natgnd_eps']:.4f}",
        f"sigma = {best.params['deep_natgnd_sigma']:.6f}\n",
        "[[sub_layers]]",
        'name  = "natgnd_upper"',
        "h     = 0.15",
        f"eps   = {best.params['natgnd_upper_eps']:.4f}",
        f"sigma = {best.params['natgnd_upper_sigma']:.6f}\n",
        "[[sub_layers]]",
        'name  = "bedrock"',
        "h     = 0.10",
        f"eps   = {best.params['bedrock_eps']:.4f}",
        "sigma = 0.001000\n",
        "[[sub_layers]]",
        'name  = "formation"',
        "h     = 0.10",
        f"eps   = {best.params['formation_eps']:.4f}",
        f"sigma = {best.params['formation_sigma']:.6f}\n",
        "[[sub_layers]]",
        'name  = "subballast"',
        "h     = 0.15",
        f"eps   = {best.params['subballast_eps']:.4f}",
        "sigma = 0.005000",
    ]
    snippet_path.write_text("\n".join(lines) + "\n")
    print(f"\nTOML snippet saved -> {snippet_path}")
    print(f"Run verify_best.py --study {args.study} to confirm in 3D.")


if __name__ == "__main__":
    main()
