#!/usr/bin/env python3
"""
Take top-N trials from an optuna calibration study and run them in 3D gprMax.

Reads the SQLite study DB produced by calibrate_layers.py, picks the top-N
trials by Pearson r, generates the corresponding 3D TOML configs (matching
the scene_3d_5layer_split_natgnd_e14 geometry), runs the full 3D FDTD, and
produces comparison plots against the real DZT trace.

Usage:
    python scripts/calibration/verify_best.py \\
        --study calib_v1 \\
        --dzt "D:/Codigo/Data/...DZT" --trace 77000 \\
        --top 3
"""
import argparse
import subprocess
import sys
import time
from pathlib import Path

import h5py
import matplotlib.pyplot as plt
import numpy as np
from scipy.signal import hilbert

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

REPO      = Path(__file__).resolve().parents[2]
STUDY_DIR = REPO / "experiments" / "calibration"
EXP_DIR   = REPO / "experiments" / "calibration" / "verify_3d"

GPRMAX_PY    = r"C:\Users\barba\.conda\envs\gprMax\python.exe"
GENERATE_SCR = REPO / "scripts" / "pipeline" / "generate_3d_scene.py"

# ── Load top-N trials from the optuna study ────────────────────────────────────
def load_top_trials(study_name: str, n: int):
    import optuna
    optuna.logging.set_verbosity(optuna.logging.WARNING)
    db_path = STUDY_DIR / f"{study_name}.db"
    study = optuna.load_study(
        study_name=study_name,
        storage=f"sqlite:///{db_path}",
    )
    complete = [t for t in study.trials if t.state.name == "COMPLETE"]
    ranked  = sorted(complete, key=lambda t: t.value)   # ascending = best r first
    return ranked[:n]


# ── Write 3D TOML for a trial ─────────────────────────────────────────────────
def write_3d_toml(trial, toml_path: Path) -> None:
    p = trial.params
    toml = f"""# Auto-generated 3D verification TOML
# Optuna study trial #{trial.number}  Pearson r = {-trial.value:.4f}
# Generated by verify_best.py

[sim]
domain_x  = 1.00
domain_y  = 0.50
domain_z  = 1.26

[source]
center_frequency = 400e6
antenna_type     = "gssi_400"
src_steps  = 1
rx_steps   = 1

[archie]
rho_w = 8.0

[materials.subgrade]
eps   = {p['deep_natgnd_eps']:.5f}
sigma = {p['deep_natgnd_sigma']:.7f}
name  = "deep_natgnd"

[[sub_layers]]
name  = "natgnd_upper"
h     = 0.15
eps   = {p['natgnd_upper_eps']:.5f}
sigma = {p['natgnd_upper_sigma']:.7f}

[[sub_layers]]
name  = "bedrock"
h     = 0.10
eps   = {p['bedrock_eps']:.5f}
sigma = 0.001000

[[sub_layers]]
name  = "formation"
h     = 0.10
eps   = {p['formation_eps']:.5f}
sigma = {p['formation_sigma']:.7f}

[[sub_layers]]
name  = "subballast"
h     = 0.15
eps   = {p['subballast_eps']:.5f}
sigma = 0.005000

[ballast]
thickness = 0.35
eps       = 4.5
sigma     = 0.001
use_rocks = false

[sleeper]
enabled = false
"""
    toml_path.write_text(toml)


# ── Run 3D gprMax via generate_3d_scene.py ────────────────────────────────────
def run_3d(toml_path: Path, in_path: Path, out_path: Path) -> bool:
    r1 = subprocess.run(
        [GPRMAX_PY, str(GENERATE_SCR),
         "--config", str(toml_path),
         "--out",    str(in_path)],
        capture_output=True,
    )
    if r1.returncode != 0:
        print(f"  generate_3d_scene.py FAILED:\n{r1.stderr.decode()[:500]}")
        return False

    r2 = subprocess.run(
        [GPRMAX_PY, "-m", "gprMax", str(in_path), "-gpu"],
        capture_output=True,
        timeout=900,
    )
    return r2.returncode == 0 and out_path.exists()


# ── Load real DZT trace ───────────────────────────────────────────────────────
def load_dzt_trace(dzt_path: str, trace_idx: int):
    raw  = np.fromfile(dzt_path, dtype=np.int32, offset=131072)
    n_tr = len(raw) // 512
    trace = raw[: n_tr * 512].reshape(n_tr, 512)[trace_idx, 2:].astype(np.float64)
    dt_ns = 50.0 / 511.0
    t = np.arange(len(trace)) * dt_ns
    return t, trace


# ── Comparison plot ───────────────────────────────────────────────────────────
def _envelope(y: np.ndarray) -> np.ndarray:
    env = np.abs(hilbert(y))
    peak = env.max() if env.max() > 0 else 1.0
    return env / peak


def plot_comparison(t_real, y_real, t_syn, y_syn, title: str, png_path: Path) -> float:
    dw_r = int(np.argmax(np.abs(y_real[:int(10 / (t_real[1]-t_real[0]))])))
    dw_s = int(np.argmax(np.abs(y_syn[:int(6 / (t_syn[1]-t_syn[0]))])))

    t_r = t_real - t_real[dw_r]
    t_s = t_syn  - t_syn[dw_s]

    norm_r = np.max(np.abs(y_real)) or 1.0
    norm_s = np.max(np.abs(y_syn))  or 1.0

    mask_r = (t_r >= 4.0) & (t_r <= 20.0)
    mask_s = (t_s >= 4.0) & (t_s <= 20.0)

    env_r = _envelope(y_real[mask_r])
    env_s_interp = np.interp(t_r[mask_r], t_s[mask_s],
                             _envelope(y_syn[mask_s]), left=0.0, right=0.0)
    r = float(np.corrcoef(env_r, env_s_interp)[0, 1])

    fig, axes = plt.subplots(2, 1, figsize=(9, 6), sharex=False)

    # Top: raw waveforms
    ax = axes[0]
    ax.plot(t_r, y_real / norm_r, lw=0.8, color="royalblue", label="Real DZT")
    ax.plot(t_s, y_syn / norm_s,  lw=0.8, color="tomato",    label="gprMax 3D")
    ax.axvspan(4, 20, alpha=0.08, color="green")
    ax.set_ylabel("Norm. amplitude")
    ax.set_title(f"{title}   envelope r={r:+.3f}")
    ax.legend(fontsize=8); ax.set_xlim(-2, 26)

    # Bottom: Hilbert envelopes (what the objective actually measures)
    ax2 = axes[1]
    ax2.plot(t_r[mask_r], env_r,         lw=1.2, color="royalblue", label="Real envelope")
    ax2.plot(t_r[mask_r], env_s_interp,  lw=1.2, color="tomato",    label="Syn envelope")
    ax2.axvspan(4, 20, alpha=0.08, color="green", label="coda window")
    ax2.set_xlabel("Time relative to DW peak (ns)")
    ax2.set_ylabel("Norm. envelope")
    ax2.legend(fontsize=8); ax2.set_xlim(-2, 26)

    fig.tight_layout()
    fig.savefig(png_path, dpi=150)
    plt.close(fig)
    return r


# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--study", default="calib_v1")
    ap.add_argument("--dzt",   required=True)
    ap.add_argument("--trace", type=int, default=77000)
    ap.add_argument("--top",   type=int, default=3)
    args = ap.parse_args()

    EXP_DIR.mkdir(parents=True, exist_ok=True)

    trials = load_top_trials(args.study, args.top)
    print(f"Loaded {len(trials)} top trials from study '{args.study}'\n")

    t_real, y_real = load_dzt_trace(args.dzt, args.trace)

    results = []
    for rank, trial in enumerate(trials, start=1):
        print(f"[{rank}/{len(trials)}] trial #{trial.number}  "
              f"2D r={-trial.value:.4f}")

        stem     = f"verify_trial{trial.number:05d}"
        toml_p   = EXP_DIR / f"{stem}.toml"
        in_p     = EXP_DIR / f"{stem}.in"
        out_p    = EXP_DIR / f"{stem}.out"
        png_p    = EXP_DIR / f"{stem}_compare.png"

        write_3d_toml(trial, toml_p)
        t0 = time.time()
        ok = run_3d(toml_p, in_p, out_p)
        elapsed = time.time() - t0
        print(f"  3D run: {'OK' if ok else 'FAILED'}  ({elapsed:.0f}s)")

        if not ok:
            results.append((rank, trial.number, -trial.value, None))
            continue

        with h5py.File(out_p, "r") as f:
            dt_syn = float(f.attrs["dt"]) * 1e9
            ey     = f["rxs/rx1/Ey"][:]
        t_syn = np.arange(len(ey)) * dt_syn

        r3d = plot_comparison(
            t_real, y_real, t_syn, -ey,   # polarity flip matches 3D convention
            f"Trial #{trial.number}", png_p
        )
        results.append((rank, trial.number, -trial.value, r3d))
        print(f"  3D Pearson r = {r3d:+.4f}  -> {png_p.name}")

    print(f"\n{'='*56}")
    print(f"{'Rank':>4}  {'trial':>6}  {'2D r':>8}  {'3D r':>8}")
    print("-"*56)
    for rank, tnum, r2d, r3d in results:
        r3d_s = f"{r3d:+.4f}" if r3d is not None else "FAILED"
        print(f"{rank:>4}  {tnum:>6}  {r2d:>+8.4f}  {r3d_s:>8}")


if __name__ == "__main__":
    main()
