#!/usr/bin/env python3
"""
Convert gprMax snapshot VTI files to NumPy NPZ archives.

Post-processing utility for EM field snapshots generated by gprMax.
Converts VTK ImageData (.vti) snapshot files into .npz archives suitable for
visualization, analysis, and PINN training.

Usage:
    python convert_snapshots.py <output_directory>

Example:
    python convert_snapshots.py ./gprmax_output
    # Converts all scan_*/scan_*_snaps*/*.vti files to scan_*_snapshots.npz
"""

import argparse
import sys
from pathlib import Path
from typing import Dict, Tuple, Optional

import numpy as np
from tqdm import tqdm

try:
    import vtk
    from vtk.util.numpy_support import vtk_to_numpy
except ImportError:
    print("Error: 'vtk' package is required. Install with: pip install vtk")
    sys.exit(1)


def extract_snapshot_fields_numpy(snapshot_path: Path) -> Tuple[np.ndarray, np.ndarray, float]:
    """
    Load VTK ImageData snapshot and extract E-field, H-field, and time.

    Parameters
    ----------
    snapshot_path : Path
        Path to .vti file (VTK ImageData format)

    Returns
    -------
    e_field : np.ndarray, shape [H, W, 3]
        Electric field components (Ex, Ey, Ez)
    h_field : np.ndarray, shape [H, W, 3]
        Magnetic field components (Hx, Hy, Hz)
    time : float
        Simulation time of this snapshot (seconds)
    """
    reader = vtk.vtkXMLImageDataReader()
    reader.SetFileName(str(snapshot_path))
    reader.ReadAllVectorsOn()
    reader.ReadAllScalarsOn()
    reader.Update()

    output = reader.GetOutput()

    # Extract field data
    e_field_vtk = output.GetPointData().GetArray("E")
    h_field_vtk = output.GetPointData().GetArray("H")
    time_array = output.GetFieldData().GetArray("Time")

    if e_field_vtk is None:
        raise ValueError(f"No 'E' field found in {snapshot_path}")
    if h_field_vtk is None:
        raise ValueError(f"No 'H' field found in {snapshot_path}")
    if time_array is None:
        raise ValueError(f"No 'Time' found in {snapshot_path}")

    e_field = vtk_to_numpy(e_field_vtk)
    h_field = vtk_to_numpy(h_field_vtk)
    time = time_array.GetValue(0)

    # Reshape to grid (assuming structured grid H×W×3)
    dims = output.GetDimensions()
    e_field = e_field.reshape(dims[1], dims[0], 3)  # (y, x, components)
    h_field = h_field.reshape(dims[1], dims[0], 3)

    # Flip y-axis to match gprMax coordinate convention
    e_field = np.flip(e_field, axis=0)
    h_field = np.flip(h_field, axis=0)

    return e_field, h_field, time


def convert_snapshots(output_dir: Path) -> Dict[str, int]:
    """
    Convert all snapshot .vti files in output_dir to .npz archives.

    Expects directory structure:
        output_dir/
        └── scan_XXXXX/
            └── scan_XXXXX_snaps*/
                ├── snap_*.vti
                ├── ...

    Creates:
        output_dir/scan_XXXXX_snapshots.npz with keys:
            - 'XXXXX_E': Electric field [n_snapshots, H, W]
            - 'XXXXX_H': Magnetic field [n_snapshots, 3, H, W]
            - 'XXXXX_times': Time values [n_snapshots]

    Parameters
    ----------
    output_dir : Path
        Root directory containing gprMax scan outputs

    Returns
    -------
    dict
        Summary: {'processed': count, 'failed': count, 'skipped': count}
    """
    output_dir = Path(output_dir)
    if not output_dir.exists():
        raise ValueError(f"Directory not found: {output_dir}")

    stats = {"processed": 0, "failed": 0, "skipped": 0}

    # Find all scan directories
    scan_dirs = sorted(output_dir.glob("scan_*"))

    for scan_dir in scan_dirs:
        if not scan_dir.is_dir():
            continue

        scan_id = scan_dir.name  # e.g., "scan_00001"
        scan_number = scan_id.split("_")[1]  # e.g., "00001"

        # Find snapshot subdirectories
        snap_subdirs = sorted(scan_dir.glob(f"{scan_id}_snaps*"))

        if not snap_subdirs:
            stats["skipped"] += 1
            continue

        all_e_fields = []
        all_h_fields = []
        all_times = []

        try:
            # Collect all snapshots from all subdirectories
            for snap_subdir in snap_subdirs:
                vti_files = sorted(snap_subdir.glob("snap_*.vti"))

                for vti_file in tqdm(vti_files, desc=f"  {snap_subdir.name}"):
                    try:
                        e_field, h_field, time = extract_snapshot_fields_numpy(vti_file)
                        all_e_fields.append(e_field)
                        all_h_fields.append(h_field)
                        all_times.append(time)
                    except Exception as e:
                        print(f"  Warning: Failed to extract {vti_file}: {e}")
                        stats["failed"] += 1

            if all_e_fields:
                # Stack all snapshots
                e_stack = np.stack(all_e_fields, axis=0)  # [n_snaps, H, W, 3]
                h_stack = np.stack(all_h_fields, axis=0)  # [n_snaps, H, W, 3]
                times_array = np.array(all_times)

                # Extract only Ez from E-field (index 2)
                e_z = e_stack[:, :, :, 2]  # [n_snaps, H, W]

                # Keep Hx, Hy (indices 0, 1) from H-field
                h_xy = h_stack[:, :, :, 0:2]  # [n_snaps, H, W, 2]

                # Save to NPZ
                npz_path = output_dir / f"{scan_id}_snapshots.npz"
                np.savez_compressed(
                    npz_path,
                    **{
                        f"{scan_number}_E": e_z.astype(np.float32),
                        f"{scan_number}_H": h_xy.astype(np.float32),
                        f"{scan_number}_times": times_array.astype(np.float32),
                    }
                )

                print(f"✓ {scan_id}: {len(all_times)} snapshots → {npz_path}")
                stats["processed"] += 1

            else:
                print(f"✗ {scan_id}: No snapshots found")
                stats["failed"] += 1

        except Exception as e:
            print(f"✗ {scan_id}: {e}")
            stats["failed"] += 1

    return stats


def main():
    parser = argparse.ArgumentParser(
        description="Convert gprMax snapshot VTI files to NumPy NPZ archives",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python convert_snapshots.py ./gprmax_output
  python convert_snapshots.py /path/to/scans
        """,
    )
    parser.add_argument(
        "output_dir",
        type=Path,
        help="Root directory containing gprMax scan outputs",
    )

    args = parser.parse_args()

    print(f"Converting snapshots in: {args.output_dir}")
    print()

    try:
        stats = convert_snapshots(args.output_dir)

        print()
        print("=" * 60)
        print(f"Processed: {stats['processed']}")
        print(f"Failed:    {stats['failed']}")
        print(f"Skipped:   {stats['skipped']}")
        print("=" * 60)

        if stats["failed"] > 0:
            sys.exit(1)

    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
