#!/usr/bin/env python3
"""
Script to update HDF5 output file titles to match the FI_class from corresponding input files.

The script reads the #title field from .in files (generated by synthetic_data_generator)
and updates the title attribute in the corresponding .out (HDF5) files.

Usage:
    python update_hdf5_titles.py <folder_path>
    
Example:
    python update_hdf5_titles.py synthetic_inputs/
"""

import os
import sys
import h5py
import argparse
from pathlib import Path


def read_title_from_input_file(input_file_path):
    """
    Read the #title field from a gprMax input file.
    
    Args:
        input_file_path: Path to the .in file
        
    Returns:
        The title string, or None if not found
    """
    try:
        with open(input_file_path, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line.startswith('#title:'):
                    # Extract everything after '#title:'
                    title = line.split(':', 1)[1].strip()
                    return title
        return None
    except Exception as e:
        print(f"  Error reading {input_file_path}: {e}")
        return None


def update_hdf5_title(hdf5_file_path, new_title):
    """
    Update the title attribute in an HDF5 file.
    
    Args:
        hdf5_file_path: Path to the .out (HDF5) file
        new_title: New title string to set
        
    Returns:
        True if successful, False otherwise
    """
    try:
        with h5py.File(hdf5_file_path, 'r+') as f:
            # HDF5 files can have title in different places
            # gprMax typically stores it as an attribute at the root
            
            # Update or create the title attribute
            if 'title' in f.attrs:
                old_title = f.attrs['title']
                if isinstance(old_title, bytes):
                    old_title = old_title.decode('utf-8')
                print(f"    Old title: '{old_title}'")
            else:
                print(f"    Title attribute not found (creating new)")
            
            # Set the new title
            f.attrs['title'] = new_title
            print(f"    New title: '{new_title}'")
            
        return True
    except Exception as e:
        print(f"  Error updating {hdf5_file_path}: {e}")
        return False


def process_folder(folder_path, dry_run=False):
    """
    Process all .out files in a folder, updating their titles from corresponding .in files.
    
    Args:
        folder_path: Path to folder containing .in and .out files
        dry_run: If True, only show what would be done without making changes
    """
    folder_path = Path(folder_path).resolve()
    
    if not folder_path.exists():
        print(f"Error: Folder does not exist: {folder_path}")
        return
    
    print(f"\n{'='*70}")
    print(f"Updating HDF5 Titles from Input Files")
    print(f"{'='*70}")
    print(f"Folder: {folder_path}")
    print(f"Mode: {'DRY RUN (no changes)' if dry_run else 'LIVE (making changes)'}")
    print(f"{'='*70}\n")
    
    # Find all .out files
    out_files = sorted(folder_path.glob('*.out'))
    
    if not out_files:
        print(f"No .out files found in {folder_path}")
        return
    
    print(f"Found {len(out_files)} .out files\n")
    
    success_count = 0
    skip_count = 0
    error_count = 0
    
    for out_file in out_files:
        # Find corresponding .in file
        in_file = out_file.with_suffix('.in')
        
        print(f"[{success_count + skip_count + error_count + 1}/{len(out_files)}] {out_file.name}")
        
        if not in_file.exists():
            print(f"  WARNING: No matching .in file found: {in_file.name}")
            skip_count += 1
            continue
        
        # Read title from input file
        title = read_title_from_input_file(in_file)
        
        if title is None:
            print(f"  WARNING: No #title found in {in_file.name}")
            skip_count += 1
            continue
        
        print(f"  Found title in {in_file.name}: '{title}'")
        
        # Update HDF5 file
        if not dry_run:
            if update_hdf5_title(out_file, title):
                success_count += 1
            else:
                error_count += 1
        else:
            print(f"  [DRY RUN] Would update title to: '{title}'")
            success_count += 1
        
        print()
    
    # Summary
    print(f"{'='*70}")
    print(f"Summary")
    print(f"{'='*70}")
    print(f"Total processed: {len(out_files)}")
    print(f"Successfully updated: {success_count}")
    print(f"Skipped: {skip_count}")
    print(f"Errors: {error_count}")
    print(f"{'='*70}\n")


def main():
    parser = argparse.ArgumentParser(
        description='Update HDF5 output file titles from corresponding input files',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s synthetic_inputs/
  %(prog)s output/ --dry-run
        """
    )
    
    parser.add_argument(
        'folder',
        help='Folder containing .in and .out file pairs'
    )
    
    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='Show what would be done without making changes'
    )
    
    args = parser.parse_args()
    
    process_folder(args.folder, dry_run=args.dry_run)


if __name__ == "__main__":
    main()
