#!/bin/bash
# Auto-generated script to create blueprints
# Generated by create_run_scripts.sh

set -e

GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Configuration
FORCE=false
SHOW=false

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -f|--force)
            FORCE=true
            shift
            ;;
        -s|--show)
            SHOW=true
            shift
            ;;
        *)
            shift
            ;;
    esac
done

BLUEPRINT_SCRIPT="/Users/alvarojeria/Codigo/Synth-GPR/scripts/tools/visualization/visualize_gprmax_blueprint.py"

if [ ! -f "$BLUEPRINT_SCRIPT" ]; then
    echo -e "${RED}Error: Blueprint script not found${NC}"
    exit 1
fi

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE} Creating Blueprints${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo "Directory: $(pwd)"
echo "Force:     $FORCE"
echo "Show:      $SHOW"
echo ""

TOTAL=$(ls -1 *.in 2>/dev/null | wc -l)

if [ "$TOTAL" -eq 0 ]; then
    echo -e "${RED}No .in files found${NC}"
    exit 1
fi

echo -e "${BLUE}Found $TOTAL .in files${NC}"
echo ""

PROCESSED=0
SKIPPED=0
FAILED=0

for in_file in *.in; do
    if [ -f "$in_file" ]; then
        basename_no_ext=$(basename "$in_file" .in)
        blueprint_file="${basename_no_ext}_blueprint.png"
        
        if [ -f "$blueprint_file" ] && [ "$FORCE" = false ]; then
            echo -e "${YELLOW}⏭️  Skipping $in_file (blueprint exists)${NC}"
            ((SKIPPED++))
            continue
        fi
        
        echo -n "Creating blueprint for $in_file [$((PROCESSED+SKIPPED+FAILED+1))/$TOTAL]... "
        
        if [ "$SHOW" = true ]; then
            if python "$BLUEPRINT_SCRIPT" "$in_file" -o "$blueprint_file" 2>&1 | grep -q "ERROR"; then
                echo -e "${RED}✗${NC}"
                ((FAILED++))
            else
                echo -e "${GREEN}✓${NC}"
                ((PROCESSED++))
            fi
        else
            if python "$BLUEPRINT_SCRIPT" "$in_file" -o "$blueprint_file" --no-show > /dev/null 2>&1; then
                echo -e "${GREEN}✓${NC}"
                ((PROCESSED++))
            else
                echo -e "${RED}✗${NC}"
                ((FAILED++))
            fi
        fi
    fi
done

echo ""
echo -e "${BLUE}========================================${NC}"
echo "Summary:"
echo "  ✅ Created:  $PROCESSED"
echo "  ⏭️  Skipped:  $SKIPPED"
echo "  ❌ Failed:   $FAILED"
echo -e "${BLUE}========================================${NC}"

if [ "$PROCESSED" -gt 0 ]; then
    echo ""
    echo -e "${GREEN}✅ Blueprints created!${NC}"
    echo ""
    echo "View blueprints:"
    echo "  open *_blueprint.png"
fi
