#!/bin/bash
# Auto-generated script to extract features
# Generated by create_run_scripts.sh

set -e

GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE} Extracting Features${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo "Directory: $(pwd)"
echo ""

# Check for .out files
OUT_COUNT=$(ls -1 *.out 2>/dev/null | wc -l)

if [ "$OUT_COUNT" -eq 0 ]; then
    echo -e "${RED}Error: No .out files found\033[0m"
    echo "Run ./run_gprmax.sh first"
    exit 1
fi

echo -e "${BLUE}Found $OUT_COUNT .out files${NC}"
echo ""

# Run feature extraction
python "/Users/alvarojeria/Codigo/Synth-GPR/create_feature_dataset.py" "$(pwd)"

if [ $? -eq 0 ]; then
    if [ -f "features.csv" ]; then
        echo ""
        echo -e "${GREEN}✅ Feature extraction complete!${NC}"
        
        FEATURE_COUNT=$(head -1 features.csv | tr ',' '\n' | wc -l)
        SAMPLE_COUNT=$(tail -n +2 features.csv | wc -l)
        
        echo ""
        echo "Statistics:"
        echo "  Features:  $FEATURE_COUNT"
        echo "  Samples:   $SAMPLE_COUNT"
        echo ""
        echo "Next step:"
        echo "  ./create_blueprints.sh"
    fi
else
    echo -e "${RED}❌ Feature extraction failed${NC}"
    exit 1
fi
