#!/bin/bash
# Auto-generated script to run gprMax simulations
# Generated by create_run_scripts.sh

# Note: Not using set -e because gprMax may return non-zero exit codes

GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Configuration
PARALLEL=${1:-1}  # Default to 1 parallel process, or use first argument
FORCE=false

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -p|--parallel)
            PARALLEL="$2"
            shift 2
            ;;
        -f|--force)
            FORCE=true
            shift
            ;;
        *)
            shift
            ;;
    esac
done

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE} Running gprMax Simulations${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo "Directory:  $(pwd)"
echo "Parallel:   $PARALLEL"
echo "Force:      $FORCE"
echo ""

TOTAL=$(ls -1 *.in 2>/dev/null | wc -l)

if [ "$TOTAL" -eq 0 ]; then
    echo -e "${RED}No .in files found${NC}"
    exit 1
fi

echo -e "${BLUE}Found $TOTAL .in files${NC}"
echo ""

PROCESSED=0
SKIPPED=0
FAILED=0

for in_file in *.in; do
    if [ -f "$in_file" ]; then
        out_file="${in_file%.in}.out"
        
        if [ -f "$out_file" ] && [ "$FORCE" = false ]; then
            echo -e "${YELLOW}⏭️  Skipping $in_file (output exists)${NC}"
            ((SKIPPED++))
            continue
        fi
        
        echo -n "Processing $in_file [$((PROCESSED+SKIPPED+FAILED+1))/$TOTAL]... "
        
        # Run gprMax and check if output file was created
        python -m gprMax "$in_file" -n "$PARALLEL" > /dev/null 2>&1
        
        # Check if .out file was created (more reliable than exit code)
        if [ -f "$out_file" ]; then
            echo -e "${GREEN}✓${NC}"
            ((PROCESSED++))
        else
            echo -e "${RED}✗${NC}"
            ((FAILED++))
        fi
    fi
done

echo ""
echo -e "${BLUE}========================================${NC}"
echo "Summary:"
echo "  ✅ Processed: $PROCESSED"
echo "  ⏭️  Skipped:   $SKIPPED"
echo "  ❌ Failed:    $FAILED"
echo -e "${BLUE}========================================${NC}"

if [ "$PROCESSED" -gt 0 ]; then
    echo ""
    echo -e "${GREEN}✅ Simulations complete!${NC}"
    echo ""
    echo "Next step:"
    echo "  ./extract_features.sh"
fi
